### PR TITLE
Add time next event in the room

### PR DESCRIPTION
**Pull request by timotme**
When a room is free, adds the time of the next events.
Few questions:
- Should we still add the "occupied soon" text ? 
- There is no enum in JS. Is there a better way of dealing with the row emote (line 52-58)? 
- Not sure how to dead with the state from the hooks when we have multiple variables.

I am not a js dev. Please feel free to criticise.

Bildschirmfoto 2019-05-21 um 09 16 25

### CODE REVIEW

**Comment by louismerlin** [comment]
Thank you so much !! I'll check your code asap.

I think the :hourglass_flowing_sand: emoji could be kept for rooms that are available less than 30 minutes, but with the 'available until' text :smile:

**Comment by timotme** [comment]
For now it is kept for rooms available for less than one hour.

**Comment by louismerlin** [comment]
Your code is awesome :ok_hand: 

I modified the `find` to a `reduce` to find the current event, so that it actually finds the end time of the last event of multiple events in a row.

To answer your question about enums, they are possible with a `switch` statement, but to the best of my knowledge they are not considered good practice (they are kind of clumsy, with `break`s and awkward indentation).

**Comment by louismerlin** [comment]
Screenshot_2019-05-21 Rooms EPFL

Does this seem good to you ? :grin:

**Comment by timotme** [comment]
Sound good  👌🏻. Thanks for the changes !

**Pull request merged**
